const siteData = {
  brand: {
    name: "BVG",
    tagline: "Berlin based aviation group",
    notice: "ATO3 게임 내 항공사 BVG의 공식 홈페이지입니다.",
  },
  hub: {
    city: "Berlin",
  },
  status: {
    label: "운항 준비 중",
    phase: "Initial network",
  },
  stats: [
    { value: "8", label: "첫 노선" },
    { value: "2", label: "운용 기종" },
    { value: "Berlin", label: "거점 도시" },
  ],
  routes: [
    {
      number: "BVG 101",
      from: "Berlin",
      to: "Paris",
      aircraft: "B727-100",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "서유럽 연결을 위한 첫 노선입니다.",
    },
    {
      number: "BVG 102",
      from: "Berlin",
      to: "London",
      aircraft: "B727-100",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "주요 비즈니스 수요를 담당하는 노선입니다.",
    },
    {
      number: "BVG 103",
      from: "Berlin",
      to: "Moscow",
      aircraft: "B727-100",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "동유럽 방면 네트워크 확장 노선입니다.",
    },
    {
      number: "BVG 104",
      from: "Berlin",
      to: "Madrid",
      aircraft: "B727-100",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "남서유럽 연결을 위한 기본 노선입니다.",
    },
    {
      number: "BVG 105",
      from: "Berlin",
      to: "Rome",
      aircraft: "B727-100",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "남유럽 주요 도시를 잇는 노선입니다.",
    },
    {
      number: "BVG 201",
      from: "Berlin",
      to: "New York",
      aircraft: "B707-320B",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "대서양 장거리 운항을 담당하는 노선입니다.",
    },
    {
      number: "BVG 202",
      from: "Berlin",
      to: "Seoul",
      aircraft: "B707-320B",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "동아시아 방면 장거리 핵심 노선입니다.",
    },
    {
      number: "BVG 203",
      from: "Berlin",
      to: "Hong Kong",
      aircraft: "B707-320B",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "아시아 네트워크 확장을 위한 장거리 노선입니다.",
    },
  ],
  destinations: [
    { city: "Paris", aircraft: "B727-100", passenger: true, cargo: false, status: "준비 중" },
    { city: "London", aircraft: "B727-100", passenger: true, cargo: false, status: "준비 중" },
    { city: "Moscow", aircraft: "B727-100", passenger: true, cargo: false, status: "준비 중" },
    { city: "Madrid", aircraft: "B727-100", passenger: true, cargo: false, status: "준비 중" },
    { city: "Rome", aircraft: "B727-100", passenger: true, cargo: false, status: "준비 중" },
    { city: "New York", aircraft: "B707-320B", passenger: true, cargo: false, status: "준비 중" },
    { city: "Seoul", aircraft: "B707-320B", passenger: true, cargo: false, status: "준비 중" },
    { city: "Hong Kong", aircraft: "B707-320B", passenger: true, cargo: false, status: "준비 중" },
  ],
  fleet: [
    {
      type: "B727-100",
      fullName: "Boeing 727-100",
      role: "유럽권 중거리 노선용",
      countLabel: "운용 예정",
      range: "Medium-range trijet",
      status: "주력 기재",
    },
    {
      type: "B707-320B",
      fullName: "Boeing 707-320B",
      role: "대륙 간 장거리 노선용",
      countLabel: "운용 예정",
      range: "Intercontinental jet",
      status: "장거리 기재",
    },
  ],
  milestones: [
    { step: "Network", title: "첫 노선 8개 편성", status: "확정" },
    { step: "Fleet", title: "B727-100 및 B707-320B 운용", status: "확정" },
    { step: "Base", title: "Berlin 기반 운항 준비", status: "진행 중" },
  ],
  contact: {
    formEndpoint: "",
    fallbackEmail: "",
  },
};
