const regularDestinations = [
  "뉴욕",
  "오사카",
  "댈러스",
  "뉴델리",
  "도쿄",
  "로마",
  "LA",
  "이스탄불",
  "마드리드",
  "광저우",
  "뭄바이",
  "디트로이트",
  "바르셀로나",
  "홍콩",
  "런던",
  "모스크바",
  "암스테르담",
  "오슬로",
  "파리",
  "베이징",
  "애틀랜타",
  "상하이",
  "보스턴",
  "샌프란시스코",
  "방콕",
  "서울",
  "카이로",
  "시카고",
  "쿠웨이트",
  "쿠알라룸푸르",
  "샬럿",
];

const siteData = {
  brand: {
    name: "BVG Aviation",
    tagline: "Berlin hub airline",
    slogan: "BVG는 행복을 싣고",
    notice:
      "BVG Aviation은 베를린을 허브로 삼아 전 세계 주요 도시를 연결하는 ATO3 가상 항공사입니다.",
  },
  company: {
    title: "BVG Aviation",
    intro:
      "BVG aviation은 베를린 시민들의 발이 되어주고 있는 베를린 교통공사의 항공 부서로, 1965년 1월부터 베를린 시민들의 날개 역할을 맡게 되었습니다. 1966년 1월부터 BVG에서 독립하여 BVG Aviation이 되었습니다.",
  },
  routes: regularDestinations.map((city) => ({
    from: "베를린",
    to: city,
    status: "운항 중",
  })),
  specialRoutes: [
    {
      name: "휴양지 순환 노선",
      path: ["베를린", "아바나", "파페에테"],
      description: "유명한 휴양지인 하바나와 파페에테로 떠나보세요!",
    },
    {
      name: "남극 항로 노선",
      path: ["베를린", "케이프타운", "크라이스트처치"],
      description: "비행기에 앉아서 남극의 모습을 구경하세요!",
    },
    {
      name: "아이슬란드 노선",
      path: ["베를린", "레이캬비크"],
      description: "복고풍의 항공기를 타고 북극으로 떠나보세요!",
    },
  ],
  servedCities: ["베를린", ...regularDestinations],
  fleet: [
    {
      type: "B707-320B",
      fullName: "Boeing 707-320B",
      maker: "Boeing",
      count: 7,
      image: "bvg-707-320b.jpg",
      description:
        "보잉 707-320B는 보잉 707 계열의 장거리형 개량 기종으로, 터보팬 엔진을 장착해 기존 707보다 항속거리와 연비가 좋아진 여객기입니다. 1950~60년대 국제선 제트 여객기 시대를 대표했으며, 대서양·태평양 장거리 노선에서 많이 사용되었습니다.",
      details: [
        "배경: 더 먼 거리와 높은 운항 효율을 원하는 항공사들의 요구에 따라 707-320을 개량해 개발됨",
        "사양: Pratt & Whitney JT3D 터보팬 엔진 4기, 항속거리 약 9,600km, 순항속도 약 900km/h, 좌석 수 약 140~180석.",
        "첫 운행: 707 계열은 1958년 10월 26일 팬암이 처음 운항했으며, 707-320B는 1960년대 초반부터 운항됨",
        "특징: 4발 장거리 제트기, 개선된 연비와 항속거리, 대륙 간 국제선 운항에 적합함",
      ],
    },
    {
      type: "DC-8-62",
      fullName: "Douglas DC-8-62",
      maker: "Douglas",
      count: 16,
      image: "bvg-dc8-62.jpg",
      description:
        "더글러스 DC-8-62는 DC-8 계열의 장거리형 여객기로, 길어진 항속거리와 개선된 효율을 바탕으로 대륙 간 노선에 사용된 4발 제트 여객기입니다.",
      details: [
        "배경: 장거리 국제선 수요에 대응하기 위해 DC-8 계열을 개량해 개발됨",
        "사양: 터보팬 엔진 4기, 장거리 국제선 운항에 적합한 항속거리와 순항 성능을 갖춤",
        "첫 운행: DC-8 계열은 1959년부터 상업 운항을 시작했으며, DC-8-62는 1960년대 후반 장거리형으로 운항됨",
        "특징: 긴 동체와 4발 엔진, 대륙 간 노선 운항에 적합한 장거리 성능",
      ],
    },
    {
      type: "DC-8-62 for BVG",
      fullName: "Douglas DC-8-62 for BVG",
      maker: "Douglas",
      count: 3,
      image: "bvg-dc8-62.jpg",
      description:
        "DC-8-62 for BVG는 BVG Aviation의 남극 항로 노선을 위해 1대 특별 제작된 장거리 사양 기종입니다. 항속거리 11,556km를 목표로 하며 베를린-케이프타운-크라이스트처치 순환 운항에 투입됩니다.",
      details: [
        "배경: 남극 항로 관광 순환 노선 운항을 위해 특별 사양으로 도입됨",
        "사양: 항속거리 11,556km, 장거리 순환 노선 운항을 고려한 BVG 전용 사양",
        "운용 목적: 베를린-케이프타운-크라이스트처치 남극 항로 노선 투입",
        "특징: BVG Aviation 전용 특별 제작기, 초장거리 관광 노선 운용에 특화됨",
      ],
    },
    {
      type: "TU-124",
      fullName: "Tupolev Tu-124",
      maker: "Tupolev",
      count: 1,
      image: "bvg-tu124.png",
      description:
        "투폴레프 Tu-124는 소련에서 개발된 단거리 제트 여객기로, Tu-104보다 작은 규모의 노선 운항을 위해 만들어진 초기 제트 여객기입니다. 짧은 거리의 도시 간 노선과 수요가 작은 구간에 맞춘 기종입니다.",
      details: [
        "배경: 중소 규모 도시를 연결할 수 있는 소형 제트 여객기 수요에 따라 개발됨",
        "사양: 후방 장착형 터보팬 엔진 2기, 단거리 노선 운항에 적합한 좌석 규모와 항속거리",
        "첫 운행: 1960년대 초반부터 상업 운항에 투입됨",
        "특징: 소형 동체, 단거리 운항 중심, 초기 제트 여객기 시대의 동유럽권 대표 기종",
      ],
    },
    {
      type: "B747-100",
      fullName: "Boeing 747-100",
      maker: "Boeing",
      count: 1,
      image: "bvg-747-100.jpg",
      description:
        "보잉 747-100은 보잉 747 계열의 최초 양산형으로, 넓은 동체와 2층 전방 객실을 갖춘 대형 장거리 여객기입니다. 대량 수송과 장거리 국제선 운항의 상징적인 기종입니다.",
      details: [
        "배경: 장거리 국제선에서 더 많은 승객을 한 번에 수송하기 위해 개발됨",
        "사양: 4발 터보팬 엔진, 광동체 구조, 대형 객실과 높은 수송 능력",
        "첫 운행: 1970년 팬암이 상업 운항을 시작함",
        "특징: 최초의 점보 제트기, 2층 전방 객실, 장거리 대량 수송에 적합함",
      ],
    },
    {
      type: "B747-200",
      fullName: "Boeing 747-200",
      maker: "Boeing",
      count: 18,
      image: "bvg-747-200.jpg",
      description:
        "보잉 747-200은 747-100을 바탕으로 성능과 운용 범위를 확대한 장거리형 대형 여객기입니다. 더 강력한 엔진과 향상된 항속거리로 국제선 장거리 노선에서 널리 사용되었습니다.",
      details: [
        "배경: 747-100보다 더 긴 항속거리와 높은 운항 성능을 원하는 항공사들의 요구에 따라 개발됨",
        "사양: 4발 터보팬 엔진, 광동체 장거리 여객기, 대형 수송 능력 보유",
        "첫 운행: 1970년대 초반부터 주요 국제선에 투입됨",
        "특징: 향상된 항속거리, 대형 객실, 장거리 고수요 노선에 적합함",
      ],
    },
    {
      type: "B747SP",
      fullName: "Boeing 747SP",
      maker: "Boeing",
      count: 30,
      image: "bvg-747sp.png",
      description:
        "보잉 747SP는 초장거리 운항을 위해 747의 동체를 짧게 줄이고 항속성능을 강화한 특별형 기종입니다. 수요는 비교적 작지만 거리가 매우 긴 노선에 맞춰 개발되었습니다.",
      details: [
        "배경: 초장거리 직항 노선 운항을 원하는 항공사들의 요구에 따라 개발됨",
        "사양: 단축 동체, 4발 터보팬 엔진, 장거리 운항에 특화된 성능",
        "첫 운행: 1976년부터 상업 운항에 투입됨",
        "특징: 짧은 동체와 긴 항속거리, 초장거리 국제선 운항에 적합함",
      ],
    },
    {
      type: "A300B4",
      fullName: "Airbus A300B4",
      maker: "Airbus",
      count: 4,
      image: "bvg-a300b4.png",
      description:
        "에어버스 A300B4는 세계 최초의 쌍발 광동체 여객기인 A300 계열의 개량형으로, 중거리 고수요 노선에 적합한 기종입니다. 넓은 객실과 효율적인 쌍발 운항이 특징입니다.",
      details: [
        "배경: 중거리 노선에서 대형 수송 능력과 높은 운항 효율을 동시에 제공하기 위해 개발됨",
        "사양: 쌍발 광동체 여객기, 중거리 노선용 객실 규모와 항속거리 보유",
        "첫 운행: A300 계열은 1974년 상업 운항을 시작했으며, B4형은 향상된 항속거리로 운용됨",
        "특징: 최초의 쌍발 광동체 계열, 효율적인 중거리 운항, 대형 객실",
      ],
    },
  ],
  disclosure: {
    headline: "BVG Aviation은 정직한 운영을 추구합니다.",
    note: "한화 환산액은 표시 효율을 위해 1달러=1,380원 기준으로 계산합니다.",
    reports: [
      {
        year: 1965,
        revenueUsdK: 391501,
        costUsdK: 377380,
        aircraftPurchaseUsdK: 801488,
        profitUsdK: 14121,
      },
      {
        year: 1966,
        revenueUsdK: 592791,
        costUsdK: 477295,
        aircraftPurchaseUsdK: 164720,
        profitUsdK: 115496,
      },
      {
        year: 1967,
        revenueUsdK: 695761,
        costUsdK: 550043,
        aircraftPurchaseUsdK: 256116,
        profitUsdK: 145718,
      },
      {
        year: 1968,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1969,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1970,
        revenueUsdK: 1385257,
        costUsdK: 1017037,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 368220,
      },
      {
        year: 1971,
        revenueUsdK: 1699539,
        costUsdK: 1216065,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 483474,
      },
      {
        year: 1972,
        revenueUsdK: 2037206,
        costUsdK: 1455429,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 581777,
      },
      {
        year: 1973,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1974,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1975,
        revenueUsdK: 3216483,
        costUsdK: 2307528,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 908955,
      },
      {
        year: 1976,
        revenueUsdK: 2651263,
        costUsdK: 2447794,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 203469,
      },
      {
        year: 1977,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1978,
        revenueUsdK: N/A,
        costUsdK: N/A,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: N/A,
      },
      {
        year: 1979,
        revenueUsdK: 4074675,
        costUsdK: 3449096,
        aircraftPurchaseUsdK: N/A,
        profitUsdK: 625679,
      },
      {
        year: 1980,
        revenueUsdK: 4521818,
        costUsdK: 3919265,
        aircraftPurchaseUsdK: 851120,
        profitUsdK: 602553,
      },
      {
        year: 1981,
        revenueUsdK: 5959817,
        costUsdK: 4655289,
        aircraftPurchaseUsdK: 2218528,
        profitUsdK: 1304528,
      },
    ],
  },
  contact: {
    formEndpoint: "",
    fallbackEmail: "",
  },
};
