const siteData = {
  brand: {
    name: "BVG Airlines",
    tagline: "Berlin based. Ready for launch.",
    notice: "본 사이트는 포트폴리오용 가상 항공사 웹사이트입니다.",
  },
  hub: {
    city: "Berlin",
    airport: "Berlin Brandenburg",
    code: "BER",
  },
  status: {
    label: "취항 준비 중",
    launchTarget: "2026 Q3",
    phase: "Route opening",
  },
  stats: [
    { value: "1", label: "초기 기재" },
    { value: "3", label: "공개 예정 노선" },
    { value: "BER", label: "허브 공항" },
  ],
  routes: [
    {
      number: "BVG 101",
      from: "Berlin",
      fromCode: "BER",
      to: "Paris",
      toCode: "CDG",
      aircraft: "B707-120",
      launch: "Route 01",
      status: "준비 중",
      passenger: true,
      cargo: false,
      note: "첫 정기편 후보 노선",
    },
    {
      number: "BVG 203",
      from: "Berlin",
      fromCode: "BER",
      to: "Rome",
      toCode: "FCO",
      aircraft: "B707-120",
      launch: "Route 02",
      status: "검토 중",
      passenger: true,
      cargo: false,
      note: "남유럽 연결 후보",
    },
    {
      number: "BVG 305",
      from: "Berlin",
      fromCode: "BER",
      to: "London",
      toCode: "LGW",
      aircraft: "B707-120",
      launch: "Route 03",
      status: "검토 중",
      passenger: true,
      cargo: false,
      note: "서유럽 주요 도시 후보",
    },
  ],
  destinations: [
    { city: "Paris", code: "CDG", passenger: true, cargo: false, status: "준비 중" },
    { city: "Rome", code: "FCO", passenger: true, cargo: false, status: "검토 중" },
    { city: "London", code: "LGW", passenger: true, cargo: false, status: "검토 중" },
    { city: "Madrid", code: "MAD", passenger: false, cargo: false, status: "후보" },
    { city: "Lisbon", code: "LIS", passenger: false, cargo: false, status: "후보" },
  ],
  fleet: [
    {
      type: "B707-120",
      fullName: "Boeing 707-120",
      role: "초기 장거리 노선용",
      countLabel: "도입 준비",
      range: "Long-range classic jet",
      status: "초기 기재",
    },
    {
      type: "B727-100",
      fullName: "Boeing 727-100",
      role: "중거리 노선 후보",
      countLabel: "검토 중",
      range: "Medium-range trijet",
      status: "후보 기재",
    },
    {
      type: "TU-124",
      fullName: "Tupolev Tu-124",
      role: "단거리 노선 후보",
      countLabel: "검토 중",
      range: "Short-range classic jet",
      status: "후보 기재",
    },
  ],
  milestones: [
    { step: "Step 01", title: "브랜드 및 초기 기재 공개", status: "완료" },
    { step: "Step 02", title: "Berlin BER 기반 운항 준비", status: "진행 중" },
    { step: "Step 03", title: "첫 정기 노선 발표", status: "예정" },
  ],
  contact: {
    formEndpoint: "",
    fallbackEmail: "",
  },
};
